# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学习\Code\python\二维码小工具\UI\批量.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatchWindow(object):
    def setupUi(self, BatchWindow):
        BatchWindow.setObjectName("BatchWindow")
        BatchWindow.resize(600, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(BatchWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(BatchWindow)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.addBtn = QtWidgets.QPushButton(BatchWindow)
        self.addBtn.setObjectName("addBtn")
        self.buttonLayout.addWidget(self.addBtn)
        self.removeBtn = QtWidgets.QPushButton(BatchWindow)
        self.removeBtn.setObjectName("removeBtn")
        self.buttonLayout.addWidget(self.removeBtn)
        self.generateBtn = QtWidgets.QPushButton(BatchWindow)
        self.generateBtn.setObjectName("generateBtn")
        self.buttonLayout.addWidget(self.generateBtn)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(BatchWindow)
        QtCore.QMetaObject.connectSlotsByName(BatchWindow)

    def retranslateUi(self, BatchWindow):
        _translate = QtCore.QCoreApplication.translate
        BatchWindow.setWindowTitle(_translate("BatchWindow", "批量生成二维码"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("BatchWindow", "内容"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("BatchWindow", "状态"))
        self.addBtn.setText(_translate("BatchWindow", "添加项目"))
        self.removeBtn.setText(_translate("BatchWindow", "删除选中"))
        self.generateBtn.setText(_translate("BatchWindow", "开始生成"))
